export const LOVE_QUOTES = [
    "À tes côtés, chaque instant devient éternel.",
    "Mon bonheur a ton prénom.",
    "Tu es mon aujourd'hui et tous mes demains.",
    "Le meilleur endroit au monde est dans tes bras.",
    "Chaque jour je t'aime davantage, aujourd'hui plus qu'hier et bien moins que demain.",
    "Mon cœur s'accélère à chaque fois que je te vois.",
    "Tu es mon soleil dans les jours de pluie.",
    "La vie est tellement plus belle avec toi.",
    "Nous deux, c'est l'évidence.",
    "Tu es la plus belle chose qui me soit arrivée.",
    "Aimer, c'est trouver sa richesse hors de soi.",
    "Avec toi, je suis exactement là où je dois être.",
    "Tu es l'une de mes raisons de sourire chaque jour.",
    "Mon endroit préféré, c'est d'être avec toi.",
    "La magie existe, je l'ai trouvée dans tes yeux.",
    "Si je devais recommencer, je te choisirais encore plus tôt.",
    "Un instant avec toi vaut mille ans ailleurs.",
    "Notre histoire est ma préférée.",
    "Le fil de ma vie est noué au tien.",
    "Dans l'océan de ma vie, tu es mon phare.",
    "Rien au monde ne vaut un de tes sourires.",
    "L'univers entier s'est accordé pour que je te trouve.",
    "T'aimer est la chose la plus facile que j'ai jamais eu à faire.",
    "Tu es la poésie que je n'ai jamais su écrire.",
    "Même le silence est doux quand je suis avec toi.",
    "Tu as fait de ma vie un rêve éveillé.",
    "Tu es la clé de mon bonheur.",
    "Mon cœur sourit à chaque fois que je pense à toi.",
    "Et soudain, toutes les chansons d'amour parlent de toi.",
    "Tu n'es pas seulement mon amour, tu es mon meilleur ami.",
    "Chaque moment à tes côtés est une bénédiction.",
    "Ta voix est mon son préféré.",
    "Je ne savais pas ce qu'était l'amour avant toi.",
    "Ton amour est mon refuge.",
    "Tu es le chef-d'œuvre de ma vie.",
    "Ton sourire est la plus belle des aurores.",
    "Je t'aime non seulement pour ce que tu es, mais pour ce que je suis quand je suis avec toi.",
    "Ma plus belle aventure, c'est nous.",
    "L'amour n'est pas de se regarder l'un l'autre, mais de regarder dans la même direction.",
    "Le temps s'arrête quand tu es dans mes bras.",
    "Toutes les étoiles du ciel ne brillent pas autant que toi.",
    "Tu es la seule personne avec qui je veux vieillir.",
    "Tu donnes de la couleur à ma vie.",
    "Mon âme a reconnu la tienne instantanément.",
    "Je pourrais te regarder pendant des heures sans m'en lasser.",
    "Ton prénom est la plus jolie chose que j'aie jamais dite.",
    "Je t'aimerai jusqu'à la fin des temps.",
    "Chaque battement de mon cœur prononce ton nom.",
    "Merci d'exister et d'être à mes côtés.",
    "Ton rire est la musique de mon âme.",
    "Mon amour pour toi grandit de seconde en seconde.",
    "Avec toi, je me sens à la maison n'importe où.",
    "J'aime tout de toi, de tes qualités à tes petites manies.",
    "Mon amour suprême, mon amour invincible.",
    "Que chaque matin m'émerveille par l'éclat de tes yeux.",
    "Seuls ensemble, le monde entier nous appartient.",
    "Tu es la lumière qui éclaire mes pensées.",
    "Je t'aime, c'est la seule vérité universelle que je connaisse.",
    "Être avec toi est mon vœu le plus cher exaucé.",
    "Je suis fou(folle) de toi, tout simplement.",
    "Rien ne me rend plus heureux(se) que ton sourire.",
    "Tout au fond de mes yeux, c'est toi que l'on lit.",
    "Même mille vies ne me suffiraient pas pour t'aimer asssez.",
    "Tes mots doux guérissent toutes mes blessures.",
    "Tu fais fondre mon cœur tous les jours.",
    "Il n'y a personne comme toi, tu es unique.",
    "Mon cœur t'a choisi(e) en un instant de certitude.",
    "Ta présence est tout ce dont j'ai besoin.",
    "Tu es mon conte de fées devenu réalité.",
    "Tu es la plus belle page du livre de ma vie.",
    "Mon amour pour toi est vaste comme l'océan.",
    "Ton baiser est la réponse à toutes mes questions.",
    "Tu as illuminé la nuit la plus sombre de mon âme.",
    "Je t'aime comme l'horizon aime la mer.",
    "Ton amour est le souffle qui m'anime.",
    "Le plus doux des voyages est celui que je fais vers toi.",
    "Je serai toujours là pour toi, à chaque souffle.",
    "Je veux parsemer ta vie de millions de bisous.",
    "Le bonheur n'existe que dans le reflet de ton regard.",
    "Ton amour donne des ailes à mon existence.",
    "Tu es mon joyau, ma plus belle rareté.",
    "Sans toi, mon cœur ne trouverait jamais son chemin.",
    "Tu m'as appris que le paradis, c'est sur terre avec toi.",
    "Mon désir de toi est infini comme le ciel d'été.",
    "En te voyant, j'ai compris pourquoi rien n'avait marché avant.",
    "Tu es l'amour dont mon âme avait toujours eu soif.",
    "Chaque regard que tu me lances me fait vaciller.",
    "Mon vœu le plus pieux est de te chérir toujours.",
    "Aucune fleur ne surpasse la tendresse de tes caresses.",
    "Au creux de ton coulette se cache mon univers entier.",
    "Tout a un sens depuis que nos destins sont entrelacés.",
    "Ta douceur est l'élixir qui rajeunit mon cœur.",
    "L'infini me semblait effrayant, avant de l'imaginer avec toi.",
    "T'aimer à l'infini, c'est le seul voyage que je veux faire.",
    "Tu es tout ce qui compte vraiment, pour aujourd'hui et toujours.",
    "J'aime chaque seconde de cette vie merveilleuse avec toi.",
    "Le monde est beau parce que tu es dedans.",
    "Nos cœurs battent sur le même tempo.",
    "Il n'y a pas assez de mots pour dire à quel point tu es mon monde.",
    "Ton amour a embelli ma réalité bien plus qu'aucun rêve."
];

export function getQuoteForMemory(memoryId: string): string {
    let hash = 0;
    for (let i = 0; i < memoryId.length; i++) {
        hash = memoryId.charCodeAt(i) + ((hash << 5) - hash);
    }
    const index = Math.abs(hash) % LOVE_QUOTES.length;
    return LOVE_QUOTES[index];
}
